### PR TITLE
PIA-1514: Location Selection Tests for tvOS

### PR DESCRIPTION
**Pull request by kp-geneva-parayno**
**Summary**
PIA-1514: Added Location Selection Tests to tvOS, Optimised KeyboardNavigator and MoveFocus, Optimised iOS Tests

### CODE REVIEW

**Review by kp-ruth-o — DISMISSED** [review]
looked into the **Tests** folder for both E2E tests and tvOS. Looks good to me!

**Review by kp-laura-sempere — DISMISSED** [review]
Great job Geneva! Looks very good 🚀 

One question: we still have the issue with one of the tvOS e2e sign in tests failing on CI: Do we know the root cause for that or not yet?

**Comment by kp-geneva-parayno** [comment]
> Great job Geneva! Looks very good 🚀
> 
> One question: we still have the issue with one of the tvOS e2e sign in tests failing on CI: Do we know the root cause for that or not yet?

Hi Laura - I'm still on it. I'll push in some changes now.

**Review by kp-laura-sempere — APPROVED** [review]
✅

**Pull request merged**
