### PR TITLE
PIA-845: Create basic target for tvOS

### PR DESCRIPTION
**Pull request by kp-said-rehouni**
**Summary**
This PR creates a basic tvOS target with a single screen

### CODE REVIEW

**Review by kp-juan-docal — DISMISSED** [review]
🚀

**Review by kp-laura-sempere — APPROVED** [review]
🚀

**Review by kp-laura-sempere — COMMENTED** [review]
@kp-said-rehouni , there is an error in the e2e tests job in CI on this branch, but not sure whether the issue is already in master or not:

**Review by kp-laura-sempere — APPROVED** [review]
✅

**Pull request merged**
